### ISSUE TITLE
Supports for kernel higher than 5.10 or at least for the new lts release 5.15

### ISSUE THREAD

**Issue by Tensa53** [lwfinger/rtl8192ee#29] opened 2022-01-14 13:11 UTC
Hi,i am trying to use this driver on kernel version that are higher than 5.10 but i am having some issues. The installation goes successful but after i reboot the system is very slow and i am not able to use sudo, audio and connectiviy also are not working. How can i fix this issue ? Right now i am on arch linux and the 5.10 kernel is not anymore in the repositories and the new lts kernel is. Can i at least get this working on the lts version 5.15 ?

**Comment by lwfinger** [comment] 2022-01-14 17:33
Why are you using this repo for this device. Does the version built into the kernel not work?

Your statement that the system is "very slow" does not provide any information that I can use to diagnose the situation. Perhaps you could use "top" to see what process is using a lot of CPU.

**Comment by Tensa53** [comment] 2022-01-14 18:23
I have a thinkpad t440p with a realtek rtl8192ee wifi board. The kernel drivers are not that good,during authentication on a network i have to redo it so many times and the connection is very unstable, especially after wake up the device from the suspension. I was using your driver and my board started working good but with the newest kernel, i am not able to install it correctly and that happens after installing it (audio stopped working,connectivity stopped working,sudo not working,the system is in general more slow than before). With the kernel version 5.10 the driver goes well but at the moment arch linux does not package it anymore. So i was asking you for help if you can try to debug the driver on newest kernel

**Comment by Tensa53** [comment] 2022-01-14 18:34
i am trying to replicate the issue. Could you tell me what information are useful to find a fix ? A check of the processes on top and what else ? Any dump of which log files ?

**Comment by lwfinger** [comment] 2022-01-14 21:40
I am currently chasing a similar problem with the rtl8188eu driver, which broke between 5.10 and 5.11. Once I find the kernel change that broke that driver, the same fix should apply here.

**Comment by Tensa53** [comment] 2022-01-14 22:07
Okay thank you but maybe i have found the solution for the standard module shipped with the kernel. The issue is especially on the wake up from suspsension and restarting the module seems kinda working. I think that your module can maybe reach higher speeds so i keep an eye on this issue. Thank you again for all your work

**Comment by lwfinger** [comment] 2022-01-15 18:06
The problem was caused by a change in the kernel that added a lock to the initialization of the regulatory domain, causing a lock dependency.

The fix is to move the regd initialization. I have pushed a fix that is not tested, but it worked for rtl8188eu, which has similar code.

**Comment by Tensa53** [comment] 2022-01-15 19:51
I have tried it on the newest lts kernel and i am not having any issue. Honestly for me it's important that at least is working on the lts one, so i can relay on it for some years without worry too much about new issues and easily rollback to it from mainline if am having issue with the integrated kernel driver. One thing that maybe i haven't understood correctly is the process of uninstallation of the module (follow the steps) :
1. go in the directory where you cloned the repo and do `make uninstall`
2. then delete the blacklist file and the load module files -`/etc/modprobe.d/50-blacklist.conf` and  /etc/modules-load.d/8192ee.conf-
Is this the correct way to do ?

**Comment by lwfinger** [comment] 2022-01-15 21:28
You need 'sudo make uninstall'. That will remove this driver. You should never need to force-load any driver. The kernel figures it out from the PCI ID, which you can see with 'lspci -nn'.

You should never delete 50-blacklist.conf, and it is not advisable to add any modules to that file. Instead create 50-rtl8192ee.conf and put 'blacklist rtl8192ee' in that file to blacklist the internal kernel driver when you want to use 8192ee.

**Closed by lwfinger** 2022-01-15 21:28 UTC
